version: "3.9"

services:
  app:
    build: .
    container_name: betteruptime-backend
    ports:
      - "8080:8080"
    environment:
      POSTGRES_CONNECTION: postgresql://uptime_user:uptime_pass@db:5432/betteruptime?sslmode=disable
    depends_on:
      - db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400M

  db:
    image: postgres:15-alpine
    container_name: betteruptime-postgres
    environment:
      POSTGRES_DB: betteruptime
      POSTGRES_USER: uptime_user
      POSTGRES_PASSWORD: uptime_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 400M
    command: >
      postgres
      -c shared_buffers=128MB
      -c max_connections=50

volumes:
  postgres_data:
